SELECT
  DB2START_TIME, TIMEZONEOFFSET, CON_LOCAL_DBASES, TOTAL_CONNECTIONS, AGENTS_REGISTERED, AGENTS_REGISTERED_TOP, 
  IDLE_AGENTS, AGENTS_FROM_POOL, AGENTS_CREATED_EMPTY_POOL, NUM_COORD_AGENTS, COORD_AGENTS_TOP, AGENTS_STOLEN,
  GW_TOTAL_CONS, GW_CUR_CONS, GW_CONS_WAIT_HOST, GW_CONS_WAIT_CLIENT, NUM_GW_CONN_SWITCHES
FROM TABLE
  (MON_GET_INSTANCE(-2))
